export { getWords } from './model/selectors/getWords'
export { requestWords } from './model/services/RequestWords'
export { requestWord } from './model/services/RequestWord'
export { wordsReducer } from './model/slice/wordsSlice'
export type { Word, WordsSchema } from './model/types/wordsSchema'
